# Build Model

In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
from datetime import datetime as dt
import bentoml


pd.set_option("display.max_columns", 100)
pd.set_option('display.max_rows', 50)

In [2]:
import os
from dotenv import load_dotenv

# --- Configuration Override for this Notebook Session ---

# 1. Load any variables from a .env file (good practice)
load_dotenv()

# 2. Define the correct DATABASE_URL for connecting from your notebook
#    (localhost on the externally mapped port 6000)
correct_database_url = "postgresql+asyncpg://liuhaochen:110799@localhost:6000/dota2"

# 3. Explicitly override the environment variable for this session.
#    This change only exists in the memory of this running notebook.
print(f"Overriding DATABASE_URL to: {correct_database_url}")
os.environ["DATABASE_URL"] = correct_database_url

# (Recommended) Also disable Loki logging for the local session if needed
os.environ["ENABLE_LOKI_LOGGING"] = "false"


# --- Verification Step ---
print("\n--- Current Environment for this Session ---")
print(f"DATABASE_URL: {os.getenv('DATABASE_URL')}")
print(f"Loki Logging Enabled: {os.getenv('ENABLE_LOKI_LOGGING')}")
print("------------------------------------------")

# Now, any code run below this cell (like your DatabaseManager)
# will use the new, correct connection string.

Overriding DATABASE_URL to: postgresql+asyncpg://liuhaochen:110799@localhost:6000/dota2

--- Current Environment for this Session ---
DATABASE_URL: postgresql+asyncpg://liuhaochen:110799@localhost:6000/dota2
Loki Logging Enabled: false
------------------------------------------

In [3]:
from dota_oracle_common.postgresql import DatabaseManager
from sqlalchemy.ext.asyncio import AsyncSession

local_session = DatabaseManager.get_session_factory()

2025-08-16 01:51:34,039 - dota_oracle_common.postgresql - INFO - Creating database engine with pool_size=10 and max_overflow=5
2025-08-16 01:51:34,094 - dota_oracle_common.postgresql - INFO - Successfully initialized database for 'dota2' at localhost

In [ ]:
from dota_oracle_common.repositories.match_repository import MatchRepository


async with local_session() as session:
    match_repo = MatchRepository(session)
    
    matches = await match_repo.get_match_details(
        relationship_fields=[
            "outcome"
        ]
    )
    
    print(f"number of matches: {len(matches)}")

In [ ]:
match_outcome_list = []
match_list = []
for match in matches:
    outcome = match.outcome
    if outcome:
        match_outcome_list.append(outcome)
        match_list.append(match)
        
        
print(f"{len(match_outcome_list)} outcomes")

In [ ]:

from dota_oracle_pipeline.feature_engineering import TeamFeatureCreator, PlayerHeroFeaturesCreator, HeroesFeatureCreator

In [ ]:
team_creator = TeamFeatureCreator()
player_hero_creator = PlayerHeroFeaturesCreator()

In [ ]:
async with local_session() as session:
    player_hero_features = await player_hero_creator.create_player_hero_features(
        session=session,
        match_instances=match_list
    )
    team_features = await team_creator.create_team_features(session, match_list)
    hero_features = HeroesFeatureCreator.create_hero_features(match_list)

In [ ]:
from dota_oracle_common.repositories.features_repository import FeaturesRepository
from dota_oracle_common.models.features import PlayerHeroFeatureTable, HeroFeaturesTable, TeamFeaturesTable

async with local_session() as session:
    feature_repo = FeaturesRepository(session)
    
    # await feature_repo.store_features(player_hero_features, PlayerHeroFeatureTable)
    await feature_repo.store_features(team_features, TeamFeaturesTable)
    await feature_repo.store_features(hero_features, HeroFeaturesTable)

In [ ]:
outcome_df = pd.DataFrame([match.model_dump() for match in match_outcome_list])
player_hero_team_df = pd.DataFrame([feature.model_dump() for feature in player_hero_features])
hero_df = pd.DataFrame([feature.model_dump() for feature in hero_features])
team_df = pd.DataFrame([feature.model_dump() for feature in team_features])

In [ ]:
outcome_df

In [ ]:
player_hero_team_df

In [ ]:
hero_df

In [4]:
from dota_oracle_pipeline.feature_transformation.feature_encoder import FeatureEncoder
from dota_oracle_common.repositories.heroes_repository import HeroesRepository

async with local_session() as session:
    heros_repo = HeroesRepository(session)
    hero_map = await heros_repo.get_hero_id_map()

In [ ]:
encoded_hero_features = FeatureEncoder.encode_hero_features(hero_features=hero_df, hero_map=hero_map)
encoded_hero_features

In [ ]:
merged_df = pd.merge(outcome_df, (pd.merge(player_hero_team_df, encoded_hero_features, how='inner')), how='inner')
merged_df

In [ ]:
df_final = merged_df.drop('match_id', axis=1)
n_total = len(df_final)
n_recent = int(n_total * 0.25)
df_recent = df_final[:n_recent]

In [ ]:
# Train Test Split
X = df_recent.drop('radiant_win', axis=1)
y = df_recent['radiant_win']

n_total = len(df_recent)
n_test = int(n_total * 0.3)

# Top 30% as test, remaining 70% as train
X_test = X.iloc[:n_test]     # First 30%
X_train = X.iloc[n_test:]    # Remaining 70%
y_test = y.iloc[:n_test]     # First 30%
y_train = y.iloc[n_test:]    # Remaining 70

In [ ]:
# Import candidate classifiers

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
import lightgbm as lgb

# import metrics

from sklearn.metrics import accuracy_score

In [ ]:
# Initialize models
models = {
    'Logistic Regression': LogisticRegression(
        random_state=42,
        max_iter=1000  # Increase if convergence issues
    ),
    
    'Random Forest': RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        n_jobs=-1  # Use all cores
    ),
    
    'XGBoost': xgb.XGBClassifier(
        random_state=42,
        eval_metric='logloss',  # Suppress warning
        n_estimators=100
    ),
    
    'LightGBM': lgb.LGBMClassifier(
        random_state=42,
        verbosity=-1,  # Suppress output
        n_estimators=100
    )
}

In [ ]:
results = {}

for name, model in models.items():
    print(f"\nTraining {name}...")
    
    # Train the model
    model.fit(X_train, y_train)
    
    # Make predictions
    y_pred = model.predict(X_test)
    y_pred_proba = model.predict_proba(X_test)[:, 1]  # For ROC-AUC
    
    # Calculate accuracy
    accuracy = accuracy_score(y_test, y_pred)
    
    # Store results
    results[name] = {
        'model': model,
        'accuracy': accuracy,
        'predictions': y_pred,
        'probabilities': y_pred_proba
    }
    
    print(f"{name} Accuracy: {accuracy:.3f} ({accuracy*100:.1f}%)")

In [ ]:
clf = models['Random Forest']
clf

In [ ]:
# Prediction with bentoml model service

In [28]:
from dota_oracle_common.models.inference.schema import VersionMetaData, PerformanceMetrics, ModelMetaData 

def save_sklearn_model(
    model,
    model_name: str,
    metadata: ModelMetaData
):
    print(f"attempting to save model {model_name}")
    saved_model = bentoml.sklearn.save_model(
        name=model_name,
        model=model, 
        signatures={'predict':{'batchable':True}},
        metadata=metadata.model_dump()
    )
    
    print(f"Model saved: {saved_model}")

In [ ]:
model_name = 'dota_oracle_pro_match_model'

feature_columns = clf.feature_names_in_.tolist()

performance = PerformanceMetrics(
    accuracy=0.551
)

version_data = VersionMetaData(
    performance_metrics=performance,
    feature_columns=feature_columns
)

metadata = metadata = ModelMetaData(
        name=model_name,
        version='0.0.1',
        trained_date=dt.now(),
        version_metadata=version_data
)

try:
    save_sklearn_model(model=clf, model_name=model_name, metadata=metadata)
    print("process complete")
except Exception as e:
    print(f"error saving model to bentoml, {e}")

# Public Matches (Crusader/Archons/Legends)

In [11]:
import pandas as pd
from pathlib import Path
F_PATH = Path("../data/publicMatches.parquet")

# Now, read the file
df = pd.read_parquet(F_PATH)

In [12]:
df

,match_id,start_time,duration,avg_rank_tier,num_rank_tier,radiant_win,radiant_team,dire_team
0,8417997209,1755262828,486,34,7,True,"[18, 22, 111, 11, 112]","[51, 85, 44, 49, 80]"
1,8417994515,1755262704,412,43,4,True,"[68, 25, 1, 101, 14]","[27, 53, 2, 41, 22]"
2,8417989610,1755262478,792,45,2,True,"[135, 53, 114, 30, 7]","[74, 129, 52, 102, 1]"
3,8417983608,1755262250,1150,51,9,True,"[59, 60, 30, 114, 75]","[101, 72, 39, 32, 42]"
4,8417982416,1755262195,649,51,5,True,"[15, 46, 2, 20, 35]","[136, 31, 74, 42, 71]"
...,...,...,...,...,...,...,...,...
99995,8415419008,1755094711,2207,42,6,False,"[128, 1, 129, 36, 121]","[21, 59, 30, 6, 26]"
99996,8415418917,1755094729,2074,42,3,False,"[129, 31, 40, 93, 105]","[128, 14, 98, 20, 39]"
99997,8415418914,1755094725,1705,54,6,False,"[42, 19, 11, 74, 22]","[2, 111, 46, 64, 86]"
99998,8415418913,1755094725,2164,34,4,False,"[17, 27, 105, 54, 42]","[47, 84, 123, 14, 53]"
99999,8415418908,1755094724,3837,43,2,True,"[89, 26, 74, 36, 53]","[30, 108, 13, 101, 8]"

In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [14]:
X = df[['radiant_team', 'dire_team', 'match_id']]
y = df['radiant_win'].astype(int)

In [15]:
X['hero_picks'] = X['radiant_team'].apply(list) + X['dire_team'].apply(list)
X

/tmp/ipykernel_4176592/1093348383.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['hero_picks'] = X['radiant_team'].apply(list) + X['dire_team'].apply(list)

,radiant_team,dire_team,match_id,hero_picks
0,"[18, 22, 111, 11, 112]","[51, 85, 44, 49, 80]",8417997209,"[18, 22, 111, 11, 112, 51, 85, 44, 49, 80]"
1,"[68, 25, 1, 101, 14]","[27, 53, 2, 41, 22]",8417994515,"[68, 25, 1, 101, 14, 27, 53, 2, 41, 22]"
2,"[135, 53, 114, 30, 7]","[74, 129, 52, 102, 1]",8417989610,"[135, 53, 114, 30, 7, 74, 129, 52, 102, 1]"
3,"[59, 60, 30, 114, 75]","[101, 72, 39, 32, 42]",8417983608,"[59, 60, 30, 114, 75, 101, 72, 39, 32, 42]"
4,"[15, 46, 2, 20, 35]","[136, 31, 74, 42, 71]",8417982416,"[15, 46, 2, 20, 35, 136, 31, 74, 42, 71]"
...,...,...,...,...
99995,"[128, 1, 129, 36, 121]","[21, 59, 30, 6, 26]",8415419008,"[128, 1, 129, 36, 121, 21, 59, 30, 6, 26]"
99996,"[129, 31, 40, 93, 105]","[128, 14, 98, 20, 39]",8415418917,"[129, 31, 40, 93, 105, 128, 14, 98, 20, 39]"
99997,"[42, 19, 11, 74, 22]","[2, 111, 46, 64, 86]",8415418914,"[42, 19, 11, 74, 22, 2, 111, 46, 64, 86]"
99998,"[17, 27, 105, 54, 42]","[47, 84, 123, 14, 53]",8415418913,"[17, 27, 105, 54, 42, 47, 84, 123, 14, 53]"
99999,"[89, 26, 74, 36, 53]","[30, 108, 13, 101, 8]",8415418908,"[89, 26, 74, 36, 53, 30, 108, 13, 101, 8]"

In [16]:
# --- SPLIT THE DATA FIRST ---
# This creates a true "unseen" test set.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {len(X_train)} matches")
print(f"Testing set size: {len(X_test)} matches")

Training set size: 80000 matches
Testing set size: 20000 matches

In [17]:
from dota_oracle_pipeline.feature_transformation.feature_encoder import FeatureEncoder

feature_encoder = FeatureEncoder()
X_train_encoded = feature_encoder.encode_hero_features(X_train[['hero_picks','match_id']], hero_map=hero_map)
X_test_encoded = feature_encoder.encode_hero_features(X_test[['hero_picks','match_id']], hero_map=hero_map)

In [18]:
X_train_encoded

,Vengeful Spirit,Windranger,Zeus,Kunkka,Lina,Lion,Shadow Shaman,Slardar,Tidehunter,Witch Doctor,Lich,Riki,Enigma,Tinker,Sniper,Necrophos,Warlock,Beastmaster,Queen of Pain,Venomancer,Faceless Void,Wraith King,Death Prophet,Phantom Assassin,Pugna,Templar Assassin,Viper,Luna,Dragon Knight,Dazzle,Clockwerk,Leshrac,Nature's Prophet,Lifestealer,Dark Seer,Clinkz,Tiny,Omniknight,Enchantress,Huskar,Night Stalker,Broodmother,Bounty Hunter,Weaver,Jakiro,Batrider,Chen,Spectre,Ancient Apparition,Doom,...,Timbersaw,Bristleback,Tusk,Skywrath Mage,Abaddon,Elder Titan,Legion Commander,Techies,Ember Spirit,Earth Spirit,Underlord,Terrorblade,Phoenix,Oracle,Winter Wyvern,Arc Warden,Monkey King,Dark Willow,Pangolier,Grimstroke,Hoodwink,Void Spirit,Snapfire,Mars,Ring Master,Dawnbreaker,Marci,Primal Beast,Muerta,Kez,Anti-Mage,Axe,Bane,Bloodseeker,Crystal Maiden,Drow Ranger,Earthshaker,Juggernaut,Mirana,Morphling,Shadow Fiend,Phantom Lancer,Puck,Pudge,Razor,Sand King,Storm Spirit,Sven,Slark,match_id
75220,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8416011300
48955,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,8416710818
44966,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,8416809914
13568,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,8417573711
92727,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,1,8415601915
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6265,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8417777919
54886,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,8416556809
76820,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8415975213
860,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,8417930316
15795,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,8417513518

In [19]:
X_test_encoded

,Vengeful Spirit,Windranger,Zeus,Kunkka,Lina,Lion,Shadow Shaman,Slardar,Tidehunter,Witch Doctor,Lich,Riki,Enigma,Tinker,Sniper,Necrophos,Warlock,Beastmaster,Queen of Pain,Venomancer,Faceless Void,Wraith King,Death Prophet,Phantom Assassin,Pugna,Templar Assassin,Viper,Luna,Dragon Knight,Dazzle,Clockwerk,Leshrac,Nature's Prophet,Lifestealer,Dark Seer,Clinkz,Tiny,Omniknight,Enchantress,Huskar,Night Stalker,Broodmother,Bounty Hunter,Weaver,Jakiro,Batrider,Chen,Spectre,Ancient Apparition,Doom,...,Timbersaw,Bristleback,Tusk,Skywrath Mage,Abaddon,Elder Titan,Legion Commander,Techies,Ember Spirit,Earth Spirit,Underlord,Terrorblade,Phoenix,Oracle,Winter Wyvern,Arc Warden,Monkey King,Dark Willow,Pangolier,Grimstroke,Hoodwink,Void Spirit,Snapfire,Mars,Ring Master,Dawnbreaker,Marci,Primal Beast,Muerta,Kez,Anti-Mage,Axe,Bane,Bloodseeker,Crystal Maiden,Drow Ranger,Earthshaker,Juggernaut,Mirana,Morphling,Shadow Fiend,Phantom Lancer,Puck,Pudge,Razor,Sand King,Storm Spirit,Sven,Slark,match_id
75721,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,...,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,8416000405
80184,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8415899114
19864,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,1,1,0,0,0,0,0,8417407616
76699,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,8415978106
92991,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,8415594902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32595,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,8417114704
29313,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8417189914
37862,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,8416991119
53421,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,8416597414
42410,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,8416875614

In [20]:
X_train_final = X_train_encoded.drop(columns='match_id').to_numpy()
X_test_final = X_test_encoded.drop(columns='match_id').to_numpy()

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression()

In [22]:
X_train_final

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(80000, 126))

In [23]:
y_train_final = y_train.to_numpy()
y_train_final

array([0, 1, 0, ..., 0, 1, 0], shape=(80000,))

In [24]:
# --- Cell 5: Train the Model ---
# Use the final, transformed training data
model.fit(X_train_final, y_train_final)
print("Model training complete!")

Model training complete!

In [25]:
y_pred = model.predict(X_test_final)
y_pred

array([1, 1, 1, ..., 1, 1, 1], shape=(20000,))

In [26]:

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy on the Test Set: {accuracy * 100:.2f}%")

Model Accuracy on the Test Set: 53.15%

In [29]:
model_name = 'dota_oracle_pub_match_model'

feature_columns = X_train.columns.tolist()

performance = PerformanceMetrics(
    accuracy=0.5315
)

version_data = VersionMetaData(
    performance_metrics=performance,
    feature_columns=feature_columns
)

metadata = metadata = ModelMetaData(
        name=model_name,
        version='0.0.1',
        trained_date=dt.now(),
        version_metadata=version_data
)

In [30]:
try:
    save_sklearn_model(model=model, model_name=model_name, metadata=metadata)
    print("process complete")
except Exception as e:
    print(f"error saving model to bentoml, {e}")

attempting to save model dota_oracle_pub_match_model

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/fs/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__("pkg_resources").declare_namespace(__name__)  # type: ignore

Model saved: Model(tag="dota_oracle_pub_match_model:civu6dt2isu2lryn")
process complete

# Test Model Endpoint

In [ ]:
from dota_oracle_common.utils import load_workspace_env
from dota_oracle_common.http_client import http_client_provider
from dota_oracle_common.models.inference import ModelMetaDataAPIResponse

load_workspace_env()

In [9]:

async with http_client_provider() as client:
    pub_metadata_endpoint = 'http://localhost:3333/metadata/public'
    try:
        response = await client.post(
            url=pub_metadata_endpoint,
            json={}
        )
        response.raise_for_status()
        validated_response = ModelMetaDataAPIResponse.model_validate(response.json())
    except Exception as e:
        print(f"Error, {e}")
        raise
    

validated_response

ModelMetaDataAPIResponse(name='dota_oracle_pub_match_model', version='0.0.1', trained_date=datetime.datetime(2025, 8, 16, 1, 55, 5, 875984), previous_version='', version_metadata=VersionMetaData(changes=[], performance_metrics=PerformanceMetrics(accuracy=0.5315, f1_score=0.0, precision=0.0, recall=0.0), feature_columns=['radiant_team', 'dire_team', 'match_id', 'hero_picks']))