# Build Model

In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
from datetime import datetime as dt
import bentoml

pd.set_option("display.max_columns", 100)
pd.set_option('display.max_rows', 50)

In [2]:
import os
from dotenv import load_dotenv

# --- Configuration Override for this Notebook Session ---

# 1. Load any variables from a .env file (good practice)
load_dotenv()

# 2. Define the correct DATABASE_URL for connecting from your notebook
#    (localhost on the externally mapped port 6000)
correct_database_url = "postgresql+asyncpg://liuhaochen:110799@localhost:6000/dota2"

# 3. Explicitly override the environment variable for this session.
#    This change only exists in the memory of this running notebook.
print(f"Overriding DATABASE_URL to: {correct_database_url}")
os.environ["DATABASE_URL"] = correct_database_url

# (Recommended) Also disable Loki logging for the local session if needed
os.environ["ENABLE_LOKI_LOGGING"] = "false"


# --- Verification Step ---
print("\n--- Current Environment for this Session ---")
print(f"DATABASE_URL: {os.getenv('DATABASE_URL')}")
print(f"Loki Logging Enabled: {os.getenv('ENABLE_LOKI_LOGGING')}")
print("------------------------------------------")

# Now, any code run below this cell (like your DatabaseManager)
# will use the new, correct connection string.

Overriding DATABASE_URL to: postgresql+asyncpg://liuhaochen:110799@localhost:6000/dota2

--- Current Environment for this Session ---
DATABASE_URL: postgresql+asyncpg://liuhaochen:110799@localhost:6000/dota2
Loki Logging Enabled: false
------------------------------------------

In [3]:
from dota_oracle_common.postgresql import DatabaseManager
from sqlalchemy.ext.asyncio import AsyncSession

local_session = DatabaseManager.get_session_factory()

2025-09-18 03:21:13,054 - dota_oracle_common.postgresql - INFO - Creating database engine with pool_size=10 and max_overflow=5
2025-09-18 03:21:13,153 - dota_oracle_common.postgresql - INFO - Successfully initialized database for 'dota2' at localhost

In [4]:
from dota_oracle_common.repositories.match_repository import MatchRepository


async with local_session() as session:
    match_repo = MatchRepository(session)
    
    matches = await match_repo.get_match_details(
        relationship_fields=[
            "outcome"
        ]
    )
    
    print(f"number of matches: {len(matches)}")

2025-09-18 03:21:23,793 - dota_oracle_common.repositories.base_repository - INFO - Retrieved 94151 records for MatchTable
2025-09-18 03:21:23,794 - dota_oracle_common.repositories.match_repository - INFO - Found 94151 MatchTable details.

number of matches: 94151

In [5]:
match_outcome_list = []
match_list = []
for match in matches:
    outcome = match.outcome
    if outcome:
        match_outcome_list.append(outcome)
        match_list.append(match)
        
        
print(f"{len(match_outcome_list)} outcomes")

93822 outcomes

In [6]:

from dota_oracle_pipeline.feature_engineering import HeroesFeatureCreator
from dota_oracle_pipeline.feature_engineering.batch import generate_player_hero_features, generate_team_features

In [7]:
hero_features = HeroesFeatureCreator.create_hero_features(match_list)
team_features = generate_team_features(match_list)
player_hero_features = generate_player_hero_features(match_list)

2025-09-18 03:23:53,567 - dota_oracle_pipeline.feature_engineering.heroes_features_creator - INFO - Created 93822 hero features

In [8]:
from dota_oracle_common.repositories.features_repository import FeaturesRepository
from dota_oracle_common.models.features import PlayerHeroFeatureTable, HeroFeaturesTable, TeamFeaturesTable

async with local_session() as session:
    feature_repo = FeaturesRepository(session)
    
    # await feature_repo.store_features(player_hero_features, PlayerHeroFeatureTable)
    await feature_repo.store_features(player_hero_features, PlayerHeroFeatureTable)
    await feature_repo.store_features(team_features, TeamFeaturesTable)
    await feature_repo.store_features(hero_features, HeroFeaturesTable)

2025-09-18 03:25:15,260 - dota_oracle_common.repositories.base_repository - INFO - Validating inputs...
2025-09-18 03:25:15,717 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 1...
2025-09-18 03:25:16,412 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 2...
2025-09-18 03:25:17,058 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 3...
2025-09-18 03:25:17,705 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 4...
2025-09-18 03:25:18,352 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 5...
2025-09-18 03:25:18,996 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 6...
2025-09-18 03:25:19,643 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 7...
2025-09-18 03:25:20,294 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 8...
2025-09-18 03:25:22,254 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 9...
2025-09-18 03:25:22,912 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 10...
2025-09-18 03:25:23,592 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 11...
2025-09-18 03:25:24,250 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 12...
2025-09-18 03:25:24,906 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 13...
2025-09-18 03:25:25,549 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 14...
2025-09-18 03:25:26,194 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 15...
2025-09-18 03:25:26,839 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 16...
2025-09-18 03:25:27,492 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 17...
2025-09-18 03:25:28,139 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 18...
2025-09-18 03:25:28,788 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 19...
2025-09-18 03:25:29,432 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 20...
2025-09-18 03:25:30,081 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 21...
2025-09-18 03:25:30,726 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 22...
2025-09-18 03:25:31,376 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 23...
2025-09-18 03:25:32,029 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 24...
2025-09-18 03:25:34,029 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 25...
2025-09-18 03:25:34,718 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 26...
2025-09-18 03:25:35,473 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 27...
2025-09-18 03:25:36,117 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 28...
2025-09-18 03:25:36,762 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 29...
2025-09-18 03:25:37,409 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 30...
2025-09-18 03:25:38,054 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 31...
2025-09-18 03:25:38,696 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 32...
2025-09-18 03:25:39,341 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 33...
2025-09-18 03:25:39,991 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 34...
2025-09-18 03:25:40,632 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 35...
2025-09-18 03:25:41,279 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 36...
2025-09-18 03:25:41,942 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 37...
2025-09-18 03:25:42,594 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 38...
2025-09-18 03:25:43,252 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 39...
2025-09-18 03:25:43,897 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 40...
2025-09-18 03:25:44,549 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 41...
2025-09-18 03:25:46,499 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 42...
2025-09-18 03:25:47,145 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 43...
2025-09-18 03:25:47,792 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 44...
2025-09-18 03:25:48,433 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 45...
2025-09-18 03:25:49,077 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 46...
2025-09-18 03:25:49,739 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 47...
2025-09-18 03:25:50,386 - dota_oracle_common.repositories.base_repository - INFO - Validating inputs...
2025-09-18 03:25:50,763 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 1...
2025-09-18 03:25:51,028 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 2...
2025-09-18 03:25:51,280 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 3...
2025-09-18 03:25:51,532 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 4...
2025-09-18 03:25:51,783 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 5...
2025-09-18 03:25:52,036 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 6...
2025-09-18 03:25:52,289 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 7...
2025-09-18 03:25:52,541 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 8...
2025-09-18 03:25:52,795 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 9...
2025-09-18 03:25:53,051 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 10...
2025-09-18 03:25:53,304 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 11...
2025-09-18 03:25:53,559 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 12...
2025-09-18 03:25:53,811 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 13...
2025-09-18 03:25:54,068 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 14...
2025-09-18 03:25:54,321 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 15...
2025-09-18 03:25:54,574 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 16...
2025-09-18 03:25:54,826 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 17...
2025-09-18 03:25:55,080 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 18...
2025-09-18 03:25:55,328 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 19...
2025-09-18 03:25:55,578 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 20...
2025-09-18 03:25:55,828 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 21...
2025-09-18 03:25:56,083 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 22...
2025-09-18 03:25:56,334 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 23...
2025-09-18 03:25:56,583 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 24...
2025-09-18 03:25:56,833 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 25...
2025-09-18 03:25:57,087 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 26...
2025-09-18 03:25:57,340 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 27...
2025-09-18 03:25:57,593 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 28...
2025-09-18 03:25:57,846 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 29...
2025-09-18 03:25:59,407 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 30...
2025-09-18 03:25:59,659 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 31...
2025-09-18 03:25:59,929 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 32...
2025-09-18 03:26:00,187 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 33...
2025-09-18 03:26:00,439 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 34...
2025-09-18 03:26:00,692 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 35...
2025-09-18 03:26:00,944 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 36...
2025-09-18 03:26:01,197 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 37...
2025-09-18 03:26:01,450 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 38...
2025-09-18 03:26:01,726 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 39...
2025-09-18 03:26:01,978 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 40...
2025-09-18 03:26:02,234 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 41...
2025-09-18 03:26:02,487 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 42...
2025-09-18 03:26:02,745 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 43...
2025-09-18 03:26:03,005 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 44...
2025-09-18 03:26:03,267 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 45...
2025-09-18 03:26:03,516 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 46...
2025-09-18 03:26:03,765 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 47...
2025-09-18 03:26:04,016 - dota_oracle_common.repositories.base_repository - INFO - Validating inputs...
2025-09-18 03:26:04,458 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 1...
2025-09-18 03:26:04,611 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 2...
2025-09-18 03:26:04,752 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 3...
2025-09-18 03:26:04,897 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 4...
2025-09-18 03:26:05,043 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 5...
2025-09-18 03:26:05,189 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 6...
2025-09-18 03:26:05,350 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 7...
2025-09-18 03:26:05,500 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 8...
2025-09-18 03:26:05,668 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 9...
2025-09-18 03:26:05,818 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 10...
2025-09-18 03:26:05,966 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 11...
2025-09-18 03:26:06,114 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 12...
2025-09-18 03:26:06,261 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 13...
2025-09-18 03:26:06,414 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 14...
2025-09-18 03:26:06,565 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 15...
2025-09-18 03:26:06,740 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 16...
2025-09-18 03:26:06,900 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 17...
2025-09-18 03:26:07,046 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 18...
2025-09-18 03:26:07,194 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 19...
2025-09-18 03:26:07,342 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 20...
2025-09-18 03:26:07,491 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 21...
2025-09-18 03:26:07,642 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 22...
2025-09-18 03:26:07,790 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 23...
2025-09-18 03:26:07,938 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 24...
2025-09-18 03:26:08,088 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 25...
2025-09-18 03:26:08,239 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 26...
2025-09-18 03:26:08,390 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 27...
2025-09-18 03:26:08,542 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 28...
2025-09-18 03:26:08,696 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 29...
2025-09-18 03:26:08,847 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 30...
2025-09-18 03:26:08,997 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 31...
2025-09-18 03:26:09,163 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 32...
2025-09-18 03:26:09,312 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 33...
2025-09-18 03:26:09,459 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 34...
2025-09-18 03:26:09,609 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 35...
2025-09-18 03:26:09,759 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 36...
2025-09-18 03:26:09,915 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 37...
2025-09-18 03:26:11,422 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 38...
2025-09-18 03:26:11,568 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 39...
2025-09-18 03:26:11,714 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 40...
2025-09-18 03:26:11,869 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 41...
2025-09-18 03:26:12,015 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 42...
2025-09-18 03:26:12,164 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 43...
2025-09-18 03:26:12,314 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 44...
2025-09-18 03:26:12,463 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 45...
2025-09-18 03:26:12,612 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 46...
2025-09-18 03:26:12,760 - dota_oracle_common.repositories.base_repository - INFO - Upserting batch 47...

In [9]:
outcome_df = pd.DataFrame([match.model_dump() for match in match_outcome_list])
player_hero_df = pd.DataFrame([feature.model_dump() for feature in player_hero_features])
hero_df = pd.DataFrame([feature.model_dump() for feature in hero_features])
team_df = pd.DataFrame([feature.model_dump() for feature in team_features])

In [13]:
outcome_df

       radiant_win    match_id
0            False  8467032540
1             True  8467029354
2             True  8467023676
3            False  8467017982
4            False  8467017632
...            ...         ...
93817        False  5999283181
93818        False  5999249937
93819        False  5999214195
93820         True  5999201501
93821         True  5999176266

[93822 rows x 2 columns]

In [14]:
player_hero_team_df = player_hero_df.merge(team_df, on=["match_id"], how='inner')

In [15]:
player_hero_team_df

,match_id,player_hero_0_win_rate,player_hero_1_win_rate,player_hero_2_win_rate,player_hero_3_win_rate,player_hero_4_win_rate,player_hero_128_win_rate,player_hero_129_win_rate,player_hero_130_win_rate,player_hero_131_win_rate,player_hero_132_win_rate,radiant_dire_matchup,radiant_win_rate,dire_win_rate
0,5999176266,0.5,0.5,0.5,0.500000,0.50,0.50,0.5,0.500000,0.50,0.5,0.500000,0.500000,0.500000
1,5999201501,0.5,0.5,0.5,0.500000,0.50,0.50,0.5,0.500000,0.50,0.5,0.500000,0.500000,0.500000
2,5999214195,0.5,0.5,0.5,0.500000,0.50,0.50,0.5,0.500000,0.50,0.5,0.500000,0.500000,0.500000
3,5999249937,0.5,0.5,0.5,1.000000,0.50,0.50,0.0,0.500000,0.50,0.5,1.000000,1.000000,0.000000
4,5999283181,0.5,0.5,0.5,0.500000,0.50,0.50,0.5,0.500000,0.50,0.5,0.500000,0.500000,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93817,8467017982,1.0,0.5,0.5,0.000000,0.50,0.00,0.5,1.000000,1.00,0.5,0.666667,0.600000,0.636364
93818,8467016284,1.0,1.0,1.0,1.000000,1.00,0.50,0.5,1.000000,0.50,0.5,0.333333,0.769231,0.500000
93819,8467023676,1.0,0.5,0.5,0.666667,0.00,0.50,0.5,0.500000,1.00,0.5,0.000000,0.400000,0.600000
93820,8467032540,0.5,1.0,0.5,0.500000,0.50,0.50,0.5,0.500000,0.50,0.5,0.500000,0.000000,0.500000
93821,8467029354,0.5,0.6,0.8,0.000000,0.55,0.65,0.3,0.384615,0.45,0.5,0.500000,0.400000,0.450000

In [14]:
hero_df

         match_id                                     hero_picks
0      8467032540    [110, 48, 63, 93, 39, 72, 128, 85, 38, 136]
1      8467029354       [18, 84, 53, 63, 49, 35, 110, 46, 68, 7]
2      8467023676     [15, 26, 128, 6, 28, 97, 70, 119, 135, 30]
3      8467017982       [1, 114, 28, 128, 89, 23, 56, 37, 2, 15]
4      8467017632     [36, 11, 102, 75, 87, 46, 22, 104, 71, 50]
...           ...                                            ...
93817  5999283181     [58, 98, 19, 42, 111, 41, 68, 96, 128, 46]
93818  5999249937  [126, 78, 109, 128, 102, 86, 96, 106, 94, 68]
93819  5999214195     [96, 123, 15, 121, 72, 23, 2, 94, 128, 30]
93820  5999201501      [68, 58, 97, 106, 19, 111, 17, 61, 88, 6]
93821  5999176266      [42, 30, 107, 52, 55, 65, 54, 7, 98, 121]

[93822 rows x 2 columns]

In [17]:
from dota_oracle_pipeline.feature_transformation.feature_encoder import FeatureEncoder
from dota_oracle_common.repositories.heroes_repository import HeroesRepository

async with local_session() as session:
    heros_repo = HeroesRepository(session)
    hero_map = await heros_repo.get_hero_id_map()

In [18]:
feature_encoder = FeatureEncoder(hero_map=hero_map)
encoded_hero_features = feature_encoder.transform_batch(hero_df)

In [19]:
merged_df = pd.merge(outcome_df, (pd.merge(player_hero_team_df, encoded_hero_features, how='inner')), how='inner')
merged_df

,radiant_win,match_id,player_hero_0_win_rate,player_hero_1_win_rate,player_hero_2_win_rate,player_hero_3_win_rate,player_hero_4_win_rate,player_hero_128_win_rate,player_hero_129_win_rate,player_hero_130_win_rate,player_hero_131_win_rate,player_hero_132_win_rate,radiant_dire_matchup,radiant_win_rate,dire_win_rate,Pudge,Razor,Sand King,Storm Spirit,Sven,Tiny,Vengeful Spirit,Windranger,Zeus,Kunkka,Lina,Lion,Shadow Shaman,Slardar,Tidehunter,Witch Doctor,Lich,Riki,Enigma,Tinker,Sniper,Necrophos,Warlock,Beastmaster,Puck,Queen of Pain,Venomancer,Faceless Void,Wraith King,Death Prophet,Phantom Assassin,Pugna,Templar Assassin,Viper,Luna,...,Drow Ranger,Earthshaker,Juggernaut,Mirana,Morphling,Shadow Fiend,Phantom Lancer,Weaver,Undying,Rubick,Disruptor,Nyx Assassin,Naga Siren,Tusk,Skywrath Mage,Abaddon,Elder Titan,Keeper of the Light,Io,Visage,Slark,Medusa,Troll Warlord,Centaur Warrunner,Magnus,Timbersaw,Bristleback,Legion Commander,Techies,Ember Spirit,Earth Spirit,Underlord,Terrorblade,Phoenix,Oracle,Winter Wyvern,Arc Warden,Monkey King,Pangolier,Grimstroke,Hoodwink,Void Spirit,Snapfire,Mars,Ring Master,Dawnbreaker,Marci,Primal Beast,Muerta,Kez
0,False,8467032540,0.5,1.00,0.5,0.500000,0.50,0.500000,0.500000,0.500000,0.50,0.5,0.500000,0.0,0.500000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0
1,True,8467029354,0.5,0.60,0.8,0.000000,0.55,0.650000,0.300000,0.384615,0.45,0.5,0.500000,0.4,0.450000,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,True,8467023676,1.0,0.50,0.5,0.666667,0.00,0.500000,0.500000,0.500000,1.00,0.5,0.000000,0.4,0.600000,0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0
3,False,8467017982,1.0,0.50,0.5,0.000000,0.50,0.000000,0.500000,1.000000,1.00,0.5,0.666667,0.6,0.636364,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0
4,False,8467017632,0.6,0.75,1.0,1.000000,0.40,0.529412,0.285714,0.500000,0.50,0.0,0.400000,0.5,0.600000,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93817,False,5999283181,0.5,0.50,0.5,0.500000,0.50,0.500000,0.500000,0.500000,0.50,0.5,0.500000,0.5,0.500000,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
93818,False,5999249937,0.5,0.50,0.5,1.000000,0.50,0.500000,0.000000,0.500000,0.50,0.5,1.000000,1.0,0.000000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
93819,False,5999214195,0.5,0.50,0.5,0.500000,0.50,0.500000,0.500000,0.500000,0.50,0.5,0.500000,0.5,0.500000,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0
93820,True,5999201501,0.5,0.50,0.5,0.500000,0.50,0.500000,0.500000,0.500000,0.50,0.5,0.500000,0.5,0.500000,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
93821,True,5999176266,0.5,0.50,0.5,0.500000,0.50,0.500000,0.500000,0.500000,0.50,0.5,0.500000,0.5,0.500000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [18]:

n_total = len(df_final)
n_recent = int(n_total * 0.25)
df_recent = df_final[:n_recent]

In [21]:


n_total = len(df_recent)
n_test = int(n_total * 0.3)

# Top 30% as test, remaining 70% as train
X_test = X.iloc[:n_test]     # First 30%
X_train = X.iloc[n_test:]    # Remaining 70%
y_test = y.iloc[:n_test]     # First 30%
y_train = y.iloc[n_test:]    # Remaining 70

In [22]:
# Import candidate classifiers

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
import lightgbm as lgb

# import metrics

from sklearn.metrics import accuracy_score

In [23]:
# Initialize models
models = {
    'Logistic Regression': LogisticRegression(
        random_state=42,
        max_iter=1000  # Increase if convergence issues
    ),
    
    'Random Forest': RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        n_jobs=-1  # Use all cores
    ),
    
    'XGBoost': xgb.XGBClassifier(
        random_state=42,
        eval_metric='logloss',  # Suppress warning
        n_estimators=100
    ),
    
    'LightGBM': lgb.LGBMClassifier(
        random_state=42,
        objective='binary',
        verbosity=-1,  # Suppress output
        n_estimators=100
    )
}

In [24]:
# ---- Reusable Training Utilities ----
from typing import Dict, Any, Tuple
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score


def evaluate_models(models: Dict[str, Any],
                    X_train, y_train, X_test, y_test) -> Tuple[Dict[str, Any], pd.DataFrame]:
    """
    Fit and evaluate a dict of models. Returns:
    - results: dict[name] = { model, accuracy, predictions, probabilities }
    - leaderboard: DataFrame with columns [name, accuracy]
    """
    results: Dict[str, Any] = {}
    rows = []
    for name, model in models.items():
        print(f"\nTraining {name}...")
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        # Some models may not have predict_proba (e.g., SVC without probability=True)
        try:
            y_proba = model.predict_proba(X_test)[:, 1]
        except Exception:
            y_proba = None
        acc = accuracy_score(y_test, y_pred)
        results[name] = {
            'model': model,
            'accuracy': acc,
            'predictions': y_pred,
            'probabilities': y_proba,
        }
        rows.append({'name': name, 'accuracy': acc})
        print(f"{name} Accuracy: {acc:.3f} ({acc*100:.1f}%)")
    leaderboard = pd.DataFrame(rows).sort_values('accuracy', ascending=False).reset_index(drop=True)
    return results, leaderboard

In [40]:
# Evaluate all models using reusable utility
results, leaderboard = evaluate_models(models, X_train, y_train, X_test, y_test)
leaderboard

Training Logistic Regression...
Logistic Regression Accuracy: 0.547 (54.7%)

Training Random Forest...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

Random Forest Accuracy: 0.546 (54.6%)

Training XGBoost...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

XGBoost Accuracy: 0.524 (52.4%)

Training LightGBM...
LightGBM Accuracy: 0.551 (55.1%)

                  name  accuracy
0             LightGBM  0.550597
1  Logistic Regression  0.546617
2        Random Forest  0.546049
3              XGBoost  0.524161

In [38]:
clf = models['Random Forest']
clf

In [39]:
# Pick best model by accuracy
def best_model(results: Dict[str, Any]) -> Tuple[str, Any]:
    name = max(results.keys(), key=lambda k: results[k]['accuracy'])
    return name, results[name]['model']

best_name, clf = best_model(results)
print(f"Selected best model: {best_name}")
clf

In [40]:
# Prediction with bentoml model service

Training Logistic Regression...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

Training Logistic Regression...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

Logistic Regression Accuracy: 0.559 (55.9%)

Training Random Forest...

Training Logistic Regression...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

Logistic Regression Accuracy: 0.559 (55.9%)

Training Random Forest...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

Training Logistic Regression...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

Logistic Regression Accuracy: 0.559 (55.9%)

Training Random Forest...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

Random Forest Accuracy: 0.551 (55.1%)

Training XGBoost...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

Training Logistic Regression...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

Logistic Regression Accuracy: 0.559 (55.9%)

Training Random Forest...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

Random Forest Accuracy: 0.551 (55.1%)

Training XGBoost...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

XGBoost Accuracy: 0.539 (53.9%)

Training LightGBM...
LightGBM Accuracy: 0.562 (56.2%)
LightGBM Accuracy: 0.562 (56.2%)

Training Logistic Regression...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

Logistic Regression Accuracy: 0.559 (55.9%)

Training Random Forest...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:919: UserWarning: pandas.DataFrame with sparse columns found.It will be converted to a dense numpy array.
  warnings.warn(

Random Forest Accuracy: 0.551 (55.1%)

Training XGBoost...

/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")
/home/ubuntu/projects/dota2pred/.venv/lib/python3.11/site-packages/xgboost/data.py:399: UserWarning: Sparse arrays from pandas are converted into dense.
  warnings.warn("Sparse arrays from pandas are converted into dense.")

XGBoost Accuracy: 0.539 (53.9%)

Training LightGBM...
LightGBM Accuracy: 0.562 (56.2%)
LightGBM Accuracy: 0.562 (56.2%)

                  name  accuracy
0             LightGBM  0.562067
1  Logistic Regression  0.558533
2        Random Forest  0.550933
3              XGBoost  0.539067

In [32]:
import shap
import matplotlib.pyplot as plt

# Provide background data to the explainer for better, faster results
explainer = shap.Explainer(models['LightGBM'], X_train)

# Handle both new (explainer(X)) and legacy (.shap_values) SHAP APIs

--- STARTING ISOLATION TEST ---

[1/5] Creating a new, isolated LGBMClassifier with objective='binary'
[2/5] Fitting the isolated model...

[3/5] Verifying the fitted model's parameters...
  - Model Objective: binary
  - Model Class: <class 'lightgbm.sklearn.LGBMClassifier'>
  - VERIFICATION SUCCEEDED: The model is definitively a binary classifier.

[4/5] Creating SHAP explainer with the verified model...
[5/5] Calculating SHAP values...

[3/5] Verifying the fitted model's parameters...
  - Model Objective: binary
  - Model Class: <class 'lightgbm.sklearn.LGBMClassifier'>
  - VERIFICATION SUCCEEDED: The model is definitively a binary classifier.

[4/5] Creating SHAP explainer with the verified model...
[5/5] Calculating SHAP values...

--- STARTING ISOLATION TEST ---

[1/5] Creating a new, isolated LGBMClassifier with objective='binary'
[2/5] Fitting the isolated model...

[3/5] Verifying the fitted model's parameters...
  - Model Objective: binary
  - Model Class: <class 'lightgbm.sklearn.LGBMClassifier'>
  - VERIFICATION SUCCEEDED: The model is definitively a binary classifier.

[4/5] Creating SHAP explainer with the verified model...
[5/5] Calculating SHAP values...

[3/5] Verifying the fitted model's parameters...
  - Model Objective: binary
  - Model Class: <class 'lightgbm.sklearn.LGBMClassifier'>
  - VERIFICATION SUCCEEDED: The model is definitively a binary classifier.

[4/5] Creating SHAP explainer with the verified model...
[5/5] Calculating SHAP values...

 56%|===========         | 8380/15000 [00:16<00:12]

In [ ]:
model_name = 'dota_oracle_pro_match_model'

feature_columns = clf.feature_names_in_.tolist()

performance = PerformanceMetrics(
    accuracy=0.551
)

version_data = VersionMetaData(
    performance_metrics=performance,
    feature_columns=feature_columns
)

metadata = metadata = ModelMetaData(
        name=model_name,
        version='0.0.1',
        trained_date=dt.now(),
        version_metadata=version_data
)

try:
    save_sklearn_model(model=clf, model_name=model_name, metadata=metadata)
    print("process complete")
except Exception as e:
    print(f"error saving model to bentoml, {e}")

# Public Matches (Crusader/Archons/Legends)

In [ ]:
import pandas as pd
from pathlib import Path
F_PATH = Path("../data/publicMatches.parquet")

# Now, read the file
df = pd.read_parquet(F_PATH)

In [32]:
df

 98%|===================| 14731/15000 [00:28<00:00]

 98%|===================| 14731/15000 [00:28<00:00]

ExplainerError: Additivity check failed in TreeExplainer! Please ensure the data matrix you passed to the explainer is the same shape that the model was trained on. If your data shape is correct then please report this on GitHub. This check failed because for one of the samples the sum of the SHAP values was -0.102408, while the model output was 0.070398. If this difference is acceptable you can set check_additivity=False to disable this check.

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
X = df[['radiant_team', 'dire_team', 'match_id']]
y = df['radiant_win'].astype(int)

In [ ]:
X['hero_picks'] = X['radiant_team'].apply(list) + X['dire_team'].apply(list)
X

In [ ]:
# --- SPLIT THE DATA FIRST ---
# This creates a true "unseen" test set.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {len(X_train)} matches")
print(f"Testing set size: {len(X_test)} matches")

In [ ]:
from dota_oracle_pipeline.feature_transformation.feature_encoder import FeatureEncoder

feature_encoder = FeatureEncoder()
X_train_encoded = feature_encoder.encode_hero_features(X_train[['hero_picks','match_id']], hero_map=hero_map)
X_test_encoded = feature_encoder.encode_hero_features(X_test[['hero_picks','match_id']], hero_map=hero_map)

In [ ]:
X_train_encoded

In [ ]:
X_test_encoded

In [ ]:
X_train_final = X_train_encoded.drop(columns='match_id').to_numpy()
X_test_final = X_test_encoded.drop(columns='match_id').to_numpy()

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression()

In [ ]:
# Optional: sklearn Pipeline example for public matches
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.linear_model import LogisticRegression

.
# Function to extract features array from encoded DataFrame
def to_numpy_features(df: pd.DataFrame) -> np.ndarray:
    return df.drop(columns='match_id').to_numpy()

.
pipe = Pipeline(steps=[
    ("to_numpy", FunctionTransformer(to_numpy_features, validate=False)),
    ("clf", LogisticRegression(max_iter=1000))
])

.
# Fit on train and evaluate on test
pipe.fit(X_train_encoded, y_train)
pipe_acc = pipe.score(X_test_encoded, y_test)
print(f"Pipeline LogisticRegression Accuracy: {pipe_acc:.3f} ({pipe_acc*100:.1f}%)")

In [ ]:
X_train_final

In [ ]:
y_train_final = y_train.to_numpy()
y_train_final

In [ ]:
# --- Cell 5: Train the Model ---
# Use the final, transformed training data
model.fit(X_train_final, y_train_final)
print("Model training complete!")

In [ ]:
y_pred = model.predict(X_test_final)
y_pred

In [ ]:

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy on the Test Set: {accuracy * 100:.2f}%")

In [ ]:
model_name = 'dota_oracle_pub_match_model'

feature_columns = X_train.columns.tolist()

performance = PerformanceMetrics(
    accuracy=0.5315
)

version_data = VersionMetaData(
    performance_metrics=performance,
    feature_columns=feature_columns
)

metadata = metadata = ModelMetaData(
        name=model_name,
        version='0.0.1',
        trained_date=dt.now(),
        version_metadata=version_data
)

In [ ]:
try:
    save_sklearn_model(model=model, model_name=model_name, metadata=metadata)
    print("process complete")
except Exception as e:
    print(f"error saving model to bentoml, {e}")

# Test Model Endpoint

In [ ]:
from dota_oracle_common.utils import load_workspace_env
from dota_oracle_common.http_client import http_client_provider
from dota_oracle_common.models.inference import ModelMetaDataAPIResponse

load_workspace_env()

In [ ]:

async with http_client_provider() as client:
    pub_metadata_endpoint = 'http://localhost:3333/metadata/public'
    try:
        response = await client.post(
            url=pub_metadata_endpoint,
            json={}
        )
        response.raise_for_status()
        validated_response = ModelMetaDataAPIResponse.model_validate(response.json())
    except Exception as e:
        print(f"Error, {e}")
        raise
    

validated_response